development:
  domain: "localhost:3000"

production:
  domain: "rationalizeitconsulting.com"
  files_domain: "material.rationalizeitconsulting.com"

# don't set a domain for the test environment, this is handled automatically by
# the specs
